### ISSUE TITLE
Metrics not gathered after ip change

### ISSUE THREAD

**Issue by gruyaume** [canonical/sdcore-amf-k8s-operator#438]
### Bug Description

When the AMF (or any other network function) changes IP address, the IP address in the `prometheus_scrape` integration (`prometheus_scrape_unit_address` unit relation data) is not updated.

> Note: This issue also occurs in mongodb, we should probably also open the bug in their repo to let the data platform team know about this situation.

### Root cause
The prometheus class only listens to relation changed which does not seem to update when the pod IP changes.

### Possible solution

We could pass `update status` as a refresh event to the  Prometheus class.

### To Reproduce

1. Deploy core network
2. Integrate with COS
3. Kill one pod

### Environment

N/A

### Relevant log output

```shell
N/A
```

### Additional context

I'm opening this bug on a different system from the one running the setup, hence the lack of logs.

**Comment by dariofaccin** [comment]
I also opened [this feature request](https://github.com/canonical/prometheus-k8s-operator/issues/644)  to address this issue.
